# Generated by Django 4.1.2 on 2022-10-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleado_delete_empleados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='nif',
            field=models.CharField(max_length=20),
        ),
    ]
